#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_3(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, LGUI_T(KC_Z), LALT_T(KC_X), LCTL_T(KC_C), LSFT_T(KC_V), KC_B, KC_N, RSFT_T(KC_M), RCTL_T(KC_COMM), RALT_T(KC_DOT), KC_SLSH, KC_ESC, KC_SPC, KC_TAB, MO(1), KC_BSPC, KC_ENT, KC_MPLY),
	[1] = LAYOUT_split_3x5_3(KC_NO, KC_7, KC_8, KC_9, KC_MINS, KC_QUOT, KC_LBRC, KC_RBRC, KC_9, KC_0, KC_NO, KC_4, KC_5, KC_6, KC_EQL, KC_BSLS, KC_LPRN, KC_RPRN, KC_CIRC, KC_NO, KC_NO, KC_1, KC_2, KC_3, MO(0), KC_TILD, KC_NO, KC_COMM, KC_DOT, KC_NO, KC_ESC, KC_SPC, KC_TAB, MO(2), KC_BSPC, KC_ENT, KC_MPLY),
	[2] = LAYOUT_split_3x5_3(KC_NO, KC_F7, KC_F8, KC_F9, KC_F10, KC_PSCR, KC_SCRL, KC_PAUS, KC_LPRN, KC_RPRN, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_INS, KC_HOME, KC_PGUP, KC_RBRC, KC_BSLS, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_DEL, KC_END, KC_PGDN, KC_RCBR, KC_PIPE, KC_ESC, KC_SPC, KC_TAB, MO(3), KC_BSPC, KC_ENT, KC_MPLY),
	[3] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_HUI, RGB_SAI, RGB_VAI, RGB_SPI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_HUD, RGB_SAD, RGB_VAD, RGB_SPD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ESC, KC_SPC, KC_TAB, KC_TRNS, KC_ENT, KC_RALT, KC_MPLY),
        [4] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [5] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [6] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [7] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
};

const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [0] =   { ENCODER_CCW_CW(KC_MS_WH_UP, KC_MS_WH_DOWN)},
    [1] =   { ENCODER_CCW_CW(RGB_HUD, RGB_HUI)  },
    [2] =   { ENCODER_CCW_CW(RGB_VAD, RGB_VAI)  },
    [3] =   { ENCODER_CCW_CW(RGB_RMOD, RGB_MOD) },
    [4] =   { ENCODER_CCW_CW(KC_NO,KC_NO)  },
    [5] =   { ENCODER_CCW_CW(KC_NO,KC_NO)  },
    [6] =   { ENCODER_CCW_CW(KC_NO,KC_NO)  },
    [7] =   { ENCODER_CCW_CW(KC_NO,KC_NO)  }
    //                  Encoder 1                                     Encoder 2
};


